# Generated by Django 5.0.1 on 2024-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('invoice_no', models.CharField(max_length=50)),
                ('profarma', models.CharField(max_length=50)),
                ('pr_no', models.CharField(max_length=50)),
                ('requisition', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(max_length=12)),
                ('invoice_date', models.DateField()),
                ('purchase_order', models.CharField(max_length=50)),
                ('pr_date', models.DateField()),
                ('material_indent', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('issuing_bank', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
