# Generated by Django 5.1 on 2024-09-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_account_no_beneficiary_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PR_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(default='', max_length=255)),
                ('address', models.TextField(default='', max_length=255)),
                ('invoice_no', models.PositiveIntegerField(default=0)),
                ('invoice_date', models.DateField()),
                ('proforma', models.CharField(default='', max_length=255)),
                ('purchase_order', models.PositiveIntegerField(default=0)),
                ('pr_no', models.PositiveIntegerField(default=0)),
                ('pr_date', models.DateField()),
                ('requisition', models.CharField(default='', max_length=255)),
                ('material_indent', models.CharField(default='', max_length=255)),
                ('project', models.CharField(default='', max_length=255)),
                ('gstin', models.CharField(default='', max_length=15)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('pan', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=50)),
                ('adhaar', models.CharField(default='', max_length=12)),
                ('account_holder', models.CharField(default='', max_length=255)),
                ('account_number', models.CharField(default='', max_length=20)),
                ('ifsc_code', models.CharField(default='', max_length=11)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('branch', models.CharField(default='', max_length=255)),
                ('upi_id', models.CharField(default='', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('tds', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('retention', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('debit_note', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('net_payable', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
